name: Request a deployment

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'rct, preprod or prod'
        default: 'rct'
        required: true
      service:
        description: 'all, user, gateway, dictionary'
        required: true
        default: 'all'
      ref:
        description: 'branch or release to deploy'
        required: true

jobs:
  request-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          environment: ${{ github.event.inputs.env }}
          ref: ${{ github.event.inputs.ref }}
          payload: '{ "service": "${{ github.event.inputs.service }}"}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
